"use client";

import { useState } from "react";
import { ArrowRight, Check, ChevronRight, Layers3, Monitor, Moon, Smartphone, Sparkles, Sun, Workflow, Zap } from "lucide-react";

/** A real, local interactive page used to capture the explicitly labelled rehearsal images. */
export default function RehearsalSource() {
  const [dark, setDark] = useState(false);
  const [mobile, setMobile] = useState(false);
  return <main data-rehearsal-source data-theme={dark ? "dark" : "light"} data-preview={mobile ? "mobile" : "desktop"} className="min-h-screen bg-[#e9edf4] text-slate-900">
    <div className="flex h-16 items-center justify-between gap-4 border-b border-slate-300 bg-white px-6"><div className="flex items-center gap-3"><span className="flex h-8 w-8 items-center justify-center rounded-lg bg-slate-950 text-white"><Layers3 size={17} /></span><div><p className="text-sm font-bold">Northstar Studio</p><p className="text-[9px] font-semibold uppercase tracking-[0.14em] text-slate-400">Local rehearsal fixture</p></div></div><div className="flex items-center gap-3"><span className="hidden text-[10px] text-slate-400 sm:block">Responsive preview</span><button type="button" aria-label="Show desktop preview" onClick={() => setMobile(false)} className={`rounded-lg border p-2 ${!mobile ? "border-blue-300 bg-blue-50 text-blue-700" : "border-slate-200 text-slate-400"}`}><Monitor size={17} /></button><span className="relative"><button type="button" aria-label="Show mobile preview" onClick={() => setMobile(true)} className={`rounded-lg border p-2 ${mobile ? "border-blue-300 bg-blue-50 text-blue-700" : dark ? "border-amber-500 bg-amber-50 text-amber-900 ring-2 ring-amber-400" : "border-slate-200 text-slate-400"}`}><Smartphone size={17} /></button>{dark && !mobile && <span className="absolute -right-2 -top-2 flex h-4 w-4 items-center justify-center rounded-full bg-amber-500 text-[9px] font-bold text-slate-950">2</span>}</span></div></div>
    <div className={mobile ? "mx-auto my-5 w-[375px] overflow-hidden rounded-[28px] border-[7px] border-slate-800 shadow-2xl" : "mx-auto"}>
      <div className={`${dark ? "bg-[#0d172c] text-slate-100" : "bg-[#f9fbff] text-[#10203c]"} ${mobile ? "min-h-[850px]" : "min-h-[calc(100vh-64px)]"}`}>
        <nav className={`flex items-center justify-between gap-5 ${mobile ? "px-5 py-5" : "mx-auto max-w-6xl px-12 py-6"}`}><span className="flex items-center gap-2 text-sm font-bold"><Sparkles size={18} className="text-blue-500" />northstar<span className="font-normal text-slate-400">studio</span></span><div className="flex items-center gap-8">{!mobile && <><span className="text-xs text-slate-500">Our approach</span><span className="text-xs text-slate-500">Selected work</span></>}<span className="relative"><button type="button" aria-label="Switch page theme" onClick={() => setDark(!dark)} className={`flex items-center gap-2 rounded-full border px-3 py-2 text-[10px] font-semibold ${dark ? "border-slate-600 bg-slate-800 text-slate-200" : "border-amber-500 bg-white text-slate-700 ring-2 ring-amber-400"}`}>{dark ? <Sun size={13} /> : <Moon size={13} />}{dark ? "Light mode" : "Dark mode"}</button>{!dark && <span className="absolute -right-2 -top-2 flex h-5 w-5 items-center justify-center rounded-full bg-amber-500 text-[10px] font-bold text-slate-950">1</span>}</span></div></nav>
        <div className={mobile ? "px-6 pb-8 pt-9" : "mx-auto max-w-6xl px-12 pb-10 pt-12"}>
          <div className={`flex items-center gap-2 ${mobile ? "text-[9px]" : "text-[10px]"} font-semibold uppercase tracking-[0.18em] text-blue-500`}><span className="h-1.5 w-1.5 rounded-full bg-blue-500" />An independent AI studio</div>
          <h1 className={`${mobile ? "mt-5 text-[43px] leading-[1.04]" : "mt-6 max-w-3xl text-[76px] leading-[1.02]"} font-semibold tracking-[-0.05em]`}>Less busywork.<br /><span className={dark ? "text-blue-400" : "text-blue-600"}>More business.</span></h1>
          <p className={`${mobile ? "mt-5 text-sm" : "mt-6 max-w-lg text-base"} leading-relaxed ${dark ? "text-slate-400" : "text-slate-500"}`}>We turn your repeatable work into reliable AI workflows. Start small. Get your time back. Build from there.</p>
          <div className={`${mobile ? "mt-7" : "mt-8"} flex items-center gap-5`}><span className="inline-flex items-center gap-3 rounded-xl bg-blue-600 px-5 py-3.5 text-xs font-semibold text-white">Find your first workflow<ArrowRight size={15} /></span>{!mobile && <span className="text-xs font-medium text-slate-500">See how we work<ChevronRight size={14} className="ml-1 inline" /></span>}</div>
          <div className={`grid ${mobile ? "mt-10 grid-cols-1 gap-3" : "mt-12 grid-cols-3 gap-4"}`}>
            {[{ title: "Find the friction", text: "Map the repetitive work that is taking your time.", icon: Zap }, { title: "Build the workflow", text: "Connect the tools you use into one useful process.", icon: Workflow }, { title: "Make it stick", text: "Test it with your team and measure the time saved.", icon: Check }].map(({ title, text, icon: Icon }, i) => <section key={title} className={`rounded-2xl border p-5 ${dark ? "border-slate-700/70 bg-[#15223a]" : "border-slate-200 bg-white"}`}><div className="mb-4 flex items-center justify-between"><Icon size={20} className={dark ? "text-blue-400" : "text-blue-600"} /><span className="font-mono text-[10px] text-slate-400">0{i + 1}</span></div><h2 className="text-sm font-semibold">{title}</h2><p className={`mt-2 text-xs leading-relaxed ${dark ? "text-slate-400" : "text-slate-500"}`}>{text}</p></section>)}
          </div>
          <p className="mt-6 text-[9px] text-slate-400">Rehearsal fixture. Fictional business. No external forms, accounts, or purchases.</p>
        </div>
      </div>
    </div>
  </main>;
}
