export default function TermsPage() {
  return (
    <div style={{ minHeight: "100vh", background: "#faf8f5", fontFamily: "'DM Sans', sans-serif" }}>
      <div style={{ maxWidth: 680, margin: "0 auto", padding: "80px 20px 60px" }}>
        <a href="/" style={{ color: "#f97316", fontSize: 13, fontWeight: 600, textDecoration: "none" }}>← Back</a>
        <h1 style={{ fontSize: 28, fontWeight: 800, color: "#1c1917", margin: "24px 0 8px", letterSpacing: "-0.02em" }}>Terms of Service</h1>
        <p style={{ fontSize: 13, color: "#a8a29e", marginBottom: 32 }}>Last updated: April 12, 2026</p>

        <div style={{ display: "flex", flexDirection: "column", gap: 24, fontSize: 14, color: "#44403c", lineHeight: 1.75 }}>
          <section>
            <h2 style={{ fontSize: 16, fontWeight: 700, color: "#1c1917", marginBottom: 8 }}>What ContextDrop is</h2>
            <p>ContextDrop is a content analysis service. You send us links to social media videos or articles, and we return AI-generated breakdowns personalized to your profile. The service is available via Telegram bot and web dashboard.</p>
          </section>

          <section>
            <h2 style={{ fontSize: 16, fontWeight: 700, color: "#1c1917", marginBottom: 8 }}>Analyses and credits</h2>
            <p>Each analysis consumes one credit. New accounts receive free credits. If an analysis fails, your credit is automatically refunded. Credits do not expire. Premium subscriptions provide additional credits and features.</p>
          </section>

          <section>
            <h2 style={{ fontSize: 16, fontWeight: 700, color: "#1c1917", marginBottom: 8 }}>AI-generated content</h2>
            <p>All breakdowns are generated by AI and may contain errors, inaccuracies, or incomplete information. ContextDrop does not guarantee the accuracy of any analysis. Always verify information independently before making decisions based on our output.</p>
          </section>

          <section>
            <h2 style={{ fontSize: 16, fontWeight: 700, color: "#1c1917", marginBottom: 8 }}>Acceptable use</h2>
            <p>Do not use ContextDrop to analyze illegal content, generate spam, or circumvent platform terms of service. We reserve the right to suspend accounts that abuse the service.</p>
          </section>

          <section>
            <h2 style={{ fontSize: 16, fontWeight: 700, color: "#1c1917", marginBottom: 8 }}>Payments</h2>
            <p>Premium subscriptions are billed monthly through Stripe. You can cancel anytime from your dashboard. Refunds for the current billing period are not provided, but you retain access until the period ends.</p>
          </section>

          <section>
            <h2 style={{ fontSize: 16, fontWeight: 700, color: "#1c1917", marginBottom: 8 }}>Changes</h2>
            <p>We may update these terms. Continued use of the service after changes constitutes acceptance.</p>
          </section>
        </div>
      </div>
    </div>
  );
}
