export default function PrivacyPage() {
  const h2 = { fontSize: 16, fontWeight: 700, color: "#1c1917", margin: "0 0 8px" } as const;
  const p = { margin: "0 0 12px" } as const;
  const ul = { paddingLeft: 20, margin: "0 0 12px" } as const;
  const li = { marginBottom: 4 } as const;

  return (
    <div style={{ minHeight: "100vh", background: "#faf8f5", fontFamily: "'DM Sans', sans-serif" }}>
      <div style={{ maxWidth: 680, margin: "0 auto", padding: "80px 20px 60px" }}>
        <a href="/" style={{ color: "#f97316", fontSize: 13, fontWeight: 600, textDecoration: "none" }}>← Back</a>
        <h1 style={{ fontSize: 28, fontWeight: 800, color: "#1c1917", margin: "24px 0 8px", letterSpacing: "-0.02em" }}>Privacy Policy</h1>
        <p style={{ fontSize: 13, color: "#a8a29e", marginBottom: 32 }}>Last updated: 3 May 2026</p>

        <div style={{ display: "flex", flexDirection: "column", gap: 28, fontSize: 14, color: "#44403c", lineHeight: 1.75 }}>

          <section>
            <p style={p}>This Privacy Policy explains how ContextDrop ("we", "us", "our") collects, uses, and protects your personal information when you use our Telegram bot, website, and dashboard at contextdrop.ai (the "Service").</p>
            <p style={p}>ContextDrop is operated by Kaan Taskent, an individual based in the United Kingdom (the "Operator"). For the purposes of UK GDPR, the Operator is the data controller responsible for your personal information.</p>
            <p style={{ margin: 0 }}>Questions? Contact us at <a href="mailto:taskentbusiness@gmail.com" style={{ color: "#f97316", textDecoration: "none", fontWeight: 600 }}>taskentbusiness@gmail.com</a>.</p>
          </section>

          <section>
            <h2 style={h2}>1. Who can use ContextDrop</h2>
            <p style={{ margin: 0 }}>You must be at least 16 years old to use ContextDrop. By using the Service, you confirm that you meet this age requirement. If we learn that we have collected personal information from someone under 16, we will delete it.</p>
          </section>

          <section>
            <h2 style={h2}>2. What information we collect</h2>
            <p style={p}><strong>Information you give us directly:</strong></p>
            <ul style={ul}>
              <li style={li}>Email address and name (when you sign in with Google)</li>
              <li style={li}>Telegram username and Telegram user ID (when you message the bot)</li>
              <li style={li}>Notion workspace details (if you choose to connect Notion)</li>
              <li style={li}>Any messages, links, or content you send to the bot or dashboard</li>
            </ul>
            <p style={p}><strong>Information generated by your use of the Service:</strong></p>
            <ul style={ul}>
              <li style={li}>Video links you submit for analysis (from Instagram, TikTok, YouTube, X, and other platforms)</li>
              <li style={li}>AI-generated verdicts, classifications, and analyses we produce from those links</li>
              <li style={li}>Chat history with the bot and dashboard</li>
              <li style={li}>Saved tasks, preferences, and settings</li>
              <li style={li}>Credit balance and usage records</li>
            </ul>
            <p style={p}><strong>Technical information:</strong></p>
            <ul style={ul}>
              <li style={li}>IP address and approximate location (city or region level)</li>
              <li style={li}>Browser type, device type, and operating system</li>
              <li style={li}>Login timestamps and session activity</li>
              <li style={li}>Cookies required for authentication (see Section 7)</li>
            </ul>
            <p style={{ margin: 0 }}>We do not collect special category data such as health information, racial or ethnic origin, political opinions, or biometric data.</p>
          </section>

          <section>
            <h2 style={h2}>3. How we use your information</h2>
            <div style={{ overflowX: "auto" }}>
              <table style={{ width: "100%", borderCollapse: "collapse", fontSize: 13 }}>
                <thead>
                  <tr style={{ borderBottom: "2px solid #e7e5e4" }}>
                    <th style={{ textAlign: "left", padding: "8px 12px 8px 0", color: "#1c1917", fontWeight: 700 }}>Purpose</th>
                    <th style={{ textAlign: "left", padding: "8px 0 8px 12px", color: "#1c1917", fontWeight: 700 }}>Legal basis (UK GDPR)</th>
                  </tr>
                </thead>
                <tbody>
                  {[
                    ["To provide the Service (analyse your links, return verdicts, sync to your dashboard)", "Performance of contract"],
                    ["To authenticate you via Google sign-in", "Performance of contract"],
                    ["To send you transactional notifications via Telegram (analysis results, errors)", "Performance of contract"],
                    ["To improve the Service, fix bugs, and develop new features", "Legitimate interest"],
                    ["To detect, prevent, and respond to abuse, fraud, or security incidents", "Legitimate interest"],
                    ["To comply with our legal obligations", "Legal obligation"],
                    ["To send marketing communications (only with your consent)", "Consent"],
                  ].map(([purpose, basis], i) => (
                    <tr key={i} style={{ borderBottom: "1px solid #f5f5f4" }}>
                      <td style={{ padding: "10px 12px 10px 0", verticalAlign: "top" }}>{purpose}</td>
                      <td style={{ padding: "10px 0 10px 12px", verticalAlign: "top", whiteSpace: "nowrap" }}>{basis}</td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
            <p style={{ margin: "12px 0 0" }}>We do not sell your personal information. We do not share your personal information with advertisers.</p>
          </section>

          <section>
            <h2 style={h2}>4. AI processing and your data</h2>
            <p style={p}>ContextDrop uses third-party AI providers (currently OpenAI and Anthropic) to analyse the video content you submit and generate verdicts.</p>
            <p style={p}><strong>What we send to AI providers:</strong></p>
            <ul style={ul}>
              <li style={li}>The transcript of the video you submitted</li>
              <li style={li}>Visual descriptions of frames from the video</li>
              <li style={li}>The metadata associated with the video (caption, hashtags, creator)</li>
              <li style={li}>Any context you provided about why you saved the video</li>
            </ul>
            <p style={p}><strong>What we do not send:</strong></p>
            <ul style={ul}>
              <li style={li}>Your email address, name, or Telegram username</li>
              <li style={li}>Your Google or Notion account details</li>
              <li style={li}>Other users' content</li>
            </ul>
            <p style={{ margin: 0 }}><strong>AI training:</strong> We do not currently train AI models on your data. If we change this practice, we will update this Privacy Policy and notify users in advance. Our AI providers (OpenAI, Anthropic) have their own data handling policies, which prohibit training on API inputs by default.</p>
          </section>

          <section>
            <h2 style={h2}>5. Who we share your information with</h2>
            <div style={{ overflowX: "auto", marginBottom: 12 }}>
              <table style={{ width: "100%", borderCollapse: "collapse", fontSize: 13 }}>
                <thead>
                  <tr style={{ borderBottom: "2px solid #e7e5e4" }}>
                    <th style={{ textAlign: "left", padding: "8px 12px 8px 0", color: "#1c1917", fontWeight: 700 }}>Third party</th>
                    <th style={{ textAlign: "left", padding: "8px 12px", color: "#1c1917", fontWeight: 700 }}>What they do</th>
                    <th style={{ textAlign: "left", padding: "8px 0 8px 12px", color: "#1c1917", fontWeight: 700 }}>Where</th>
                  </tr>
                </thead>
                <tbody>
                  {[
                    ["Supabase", "Database and authentication hosting", "US, EU"],
                    ["Vercel", "Web dashboard hosting", "US, global edge"],
                    ["Railway", "Telegram bot hosting", "United States"],
                    ["OpenAI", "AI content analysis and verdict generation", "United States"],
                    ["Anthropic", "AI content analysis and verdict generation", "United States"],
                    ["Apify", "Video metadata and content scraping", "US, EU"],
                    ["Google", "Authentication (Sign in with Google)", "US, global"],
                    ["Notion", "Optional task export integration", "United States"],
                    ["Stripe (when payments launch)", "Payment processing", "US, EU"],
                  ].map(([name, what, where], i) => (
                    <tr key={i} style={{ borderBottom: "1px solid #f5f5f4" }}>
                      <td style={{ padding: "10px 12px 10px 0", verticalAlign: "top", fontWeight: 600 }}>{name}</td>
                      <td style={{ padding: "10px 12px", verticalAlign: "top" }}>{what}</td>
                      <td style={{ padding: "10px 0 10px 12px", verticalAlign: "top", whiteSpace: "nowrap" }}>{where}</td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
            <p style={{ margin: 0 }}>We may also share your information when required by law, to protect the rights or safety of ContextDrop or its users, or in connection with a business transfer (in which case you will be notified).</p>
          </section>

          <section>
            <h2 style={h2}>6. International data transfers</h2>
            <p style={p}>Most of our service providers are based in the United States. When we transfer your personal information outside the UK or EEA, we rely on the UK's adequacy decisions, standard contractual clauses (SCCs) approved by the UK ICO, or the UK Extension to the EU-US Data Privacy Framework where applicable.</p>
            <p style={{ margin: 0 }}>You can request a copy of the safeguards we use by emailing <a href="mailto:taskentbusiness@gmail.com" style={{ color: "#f97316", textDecoration: "none" }}>taskentbusiness@gmail.com</a>.</p>
          </section>

          <section>
            <h2 style={h2}>7. Cookies</h2>
            <p style={p}>We use cookies for one purpose: keeping you signed in. Specifically:</p>
            <ul style={ul}>
              <li style={li}>A session cookie set by Supabase Auth when you sign in with Google</li>
              <li style={li}>A short-lived cookie used during the OAuth login flow</li>
            </ul>
            <p style={{ margin: 0 }}>We do not use marketing cookies, advertising trackers, or analytics cookies that identify individual users.</p>
          </section>

          <section>
            <h2 style={h2}>8. How long we keep your data</h2>
            <div style={{ overflowX: "auto" }}>
              <table style={{ width: "100%", borderCollapse: "collapse", fontSize: 13 }}>
                <thead>
                  <tr style={{ borderBottom: "2px solid #e7e5e4" }}>
                    <th style={{ textAlign: "left", padding: "8px 12px 8px 0", color: "#1c1917", fontWeight: 700 }}>Data</th>
                    <th style={{ textAlign: "left", padding: "8px 0 8px 12px", color: "#1c1917", fontWeight: 700 }}>Retention period</th>
                  </tr>
                </thead>
                <tbody>
                  {[
                    ["Account information (email, name, Telegram ID)", "Until you delete your account"],
                    ["Saved analyses and chat history", "Until you delete them or delete your account"],
                    ["Authentication logs", "90 days"],
                    ["Backup copies", "30 days after deletion from the live database"],
                    ["Records required for tax or legal reasons", "Up to 7 years after account closure"],
                  ].map(([data, retention], i) => (
                    <tr key={i} style={{ borderBottom: "1px solid #f5f5f4" }}>
                      <td style={{ padding: "10px 12px 10px 0", verticalAlign: "top" }}>{data}</td>
                      <td style={{ padding: "10px 0 10px 12px", verticalAlign: "top" }}>{retention}</td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          </section>

          <section>
            <h2 style={h2}>9. Your rights under UK GDPR</h2>
            <p style={p}>You have the following rights regarding your personal information:</p>
            <ul style={ul}>
              <li style={li}><strong>Right of access</strong> — request a copy of the personal information we hold about you</li>
              <li style={li}><strong>Right to rectification</strong> — ask us to correct inaccurate or incomplete information</li>
              <li style={li}><strong>Right to erasure</strong> — ask us to delete your personal information</li>
              <li style={li}><strong>Right to restriction</strong> — ask us to limit how we use your information</li>
              <li style={li}><strong>Right to data portability</strong> — request your information in a machine-readable format</li>
              <li style={li}><strong>Right to object</strong> — object to processing based on legitimate interests</li>
              <li style={li}><strong>Right to withdraw consent</strong> — withdraw any consent you previously gave</li>
              <li style={li}><strong>Right to complain</strong> — lodge a complaint with the UK ICO at <a href="https://ico.org.uk" style={{ color: "#f97316", textDecoration: "none" }}>ico.org.uk</a></li>
            </ul>
            <p style={{ margin: 0 }}>To exercise any of these rights, email <a href="mailto:taskentbusiness@gmail.com" style={{ color: "#f97316", textDecoration: "none" }}>taskentbusiness@gmail.com</a>. We will respond within one calendar month.</p>
          </section>

          <section>
            <h2 style={h2}>10. Security</h2>
            <p style={p}>We use technical and organisational measures to protect your information, including encrypted connections (HTTPS), encrypted storage at the database level, access controls, and regular security review of third-party providers.</p>
            <p style={{ margin: 0 }}>No system is perfectly secure. If we become aware of a personal data breach that affects your rights, we will notify you and the ICO as required by UK GDPR.</p>
          </section>

          <section>
            <h2 style={h2}>11. Children's privacy</h2>
            <p style={{ margin: 0 }}>ContextDrop is not intended for users under 16. We do not knowingly collect personal information from children under 16. If you believe a child has provided us with personal information, contact us and we will delete it.</p>
          </section>

          <section>
            <h2 style={h2}>12. Changes to this policy</h2>
            <p style={{ margin: 0 }}>We may update this Privacy Policy from time to time. When we make material changes, we will update the "Last updated" date and notify you via email or in-app notification before the changes take effect. Continued use of the Service after changes take effect constitutes acceptance of the updated policy.</p>
          </section>

          <section>
            <h2 style={h2}>13. Contact</h2>
            <p style={p}><strong>Email:</strong> <a href="mailto:taskentbusiness@gmail.com" style={{ color: "#f97316", textDecoration: "none" }}>taskentbusiness@gmail.com</a></p>
            <p style={p}><strong>Operator:</strong> Kaan Taskent (operating as ContextDrop)</p>
            <p style={{ margin: 0 }}><strong>Country:</strong> United Kingdom</p>
          </section>

        </div>
      </div>
    </div>
  );
}
